server.port=8081
countries= India, Brazil, Russia, United States, England, Mexico, West Indies
languages = Python, Java, Go, JavaScript, Rust, Typescript
systems= Mac , Microsoft Windows, Linux, Parrot, Ios, Android